"""add_target_issue_and_sets_to_exercises

Revision ID: 321405ef920c
Revises: ffdb84d435f1
Create Date: 2026-08-17 20:26:45.928477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321405ef920c'
down_revision: Union[str, Sequence[str], None] = 'ffdb84d435f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('target_issue', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('sets', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'sets')
    op.drop_column('exercises', 'target_issue')
    # ### end Alembic commands ###
