"""Add live exercise tracking fields

Revision ID: c969fcebe36d
Revises: 321405ef920c
Create Date: 2026-08-17 22:20:30.294456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c969fcebe36d'
down_revision: Union[str, Sequence[str], None] = '321405ef920c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_reps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_reps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('form_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_sessions', schema=None) as batch_op:
        batch_op.drop_column('feedback')
        batch_op.drop_column('duration')
        batch_op.drop_column('form_score')
        batch_op.drop_column('target_reps')
        batch_op.drop_column('completed_reps')

    # ### end Alembic commands ###
