"""Add Rehab Plan models

Revision ID: d3baf473c189
Revises: df7489394ee5
Create Date: 2026-07-13 21:50:08.709295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3baf473c189'
down_revision: Union[str, Sequence[str], None] = 'df7489394ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rehab_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rehab_plans_id'), 'rehab_plans', ['id'], unique=False)
    op.create_table('exercise_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['rehab_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_sessions_id'), 'exercise_sessions', ['id'], unique=False)
    op.create_table('plan_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['rehab_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_exercises_id'), 'plan_exercises', ['id'], unique=False)
    op.add_column('exercises', sa.Column('target_muscle', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('difficulty', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('instructions', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('common_mistakes', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('tips', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('safety_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'safety_notes')
    op.drop_column('exercises', 'tips')
    op.drop_column('exercises', 'common_mistakes')
    op.drop_column('exercises', 'instructions')
    op.drop_column('exercises', 'difficulty')
    op.drop_column('exercises', 'target_muscle')
    op.drop_index(op.f('ix_plan_exercises_id'), table_name='plan_exercises')
    op.drop_table('plan_exercises')
    op.drop_index(op.f('ix_exercise_sessions_id'), table_name='exercise_sessions')
    op.drop_table('exercise_sessions')
    op.drop_index(op.f('ix_rehab_plans_id'), table_name='rehab_plans')
    op.drop_table('rehab_plans')
    # ### end Alembic commands ###
